import { v4 as uuidv4 } from 'uuid';
import { type Product } from '../types';

export const products: Product[] = [
    {id: uuidv4(), price: 150000, title: 'Домик в деревне', description: 'Просторный домик в живописном месте.', image: 'house_1.jpg', shortDescription: 'Деревенский уют.', category: 'House'},
    {id: uuidv4(), price: 800000, title: 'Семейный седан', description: 'Комфортный семейный автомобиль.', image: 'car_1.jpg', shortDescription: 'Безопасность и комфорт.', category: 'Car'},
    {id: uuidv4(), price: 10000, title: 'Мужская рубашка', description: 'Классический мужской костюм.', image: 'human_1.jpg', shortDescription: 'Стильный образ.', category: 'Human'},
    {id: uuidv4(), price: 120000, title: 'Двухэтажный коттедж', description: 'Современный двухэтажный коттедж.', image: 'house_2.jpg', shortDescription: 'Простор и удобство.', category: 'House'},
    {id: uuidv4(), price: 600000, title: 'Спортивный автомобиль', description: 'Быстрая спортивная машина.', image: 'car_2.jpg', shortDescription: 'Скорость и динамика.', category: 'Car'},
    {id: uuidv4(), price: 8000, title: 'Женские туфли', description: 'Модные женские туфли.', image: 'human_2.jpg', shortDescription: 'Стильные аксессуары.', category: 'Human'},
    {id: uuidv4(), price: 180000, title: 'Частный особняк', description: 'Эксклюзивный частный особняк.', image: 'house_3.jpg', shortDescription: 'Премиальное жилье.', category: 'House'},
    {id: uuidv4(), price: 1200000, title: 'Люксовый внедорожник', description: 'Представительный люксовый внедорожник.', image: 'car_3.jpg', shortDescription: 'Отражение статуса.', category: 'Car'},
    {id: uuidv4(), price: 15000, title: 'Детская одежда', description: 'Яркая детская одежда.', image: 'human_3.jpg', shortDescription: 'Цвет детства.', category: 'Human'},
    {id: uuidv4(), price: 250000, title: 'Апартаменты в центре города', description: 'Центральные апартаменты.', image: 'house_4.jpg', shortDescription: 'Жизнь в сердце города.', category: 'House'},
    {id: uuidv4(), price: 900000, title: 'Бизнес-класс авто', description: 'Машина премиум-класса.', image: 'car_4.jpg', shortDescription: 'Элегантность и мощь.', category: 'Car'},
    {id: uuidv4(), price: 20000, title: 'Набор детской мебели', description: 'Красивый детский гарнитур.', image: 'human_4.jpg', shortDescription: 'Удобства для малышей.', category: 'Human'},
    {id: uuidv4(), price: 300000, title: 'Таунхаус', description: 'Практичный таунхаус.', image: 'house_5.jpg', shortDescription: 'Совмещенный комфорт.', category: 'House'},
    {id: uuidv4(), price: 500000, title: 'Минивэн', description: 'Многофункциональный минивэн.', image: 'car_5.jpg', shortDescription: 'Всегда уместен.', category: 'Car'},
    {id: uuidv4(), price: 12000, title: 'Джинсовые брюки', description: 'Современные джинсы.', image: 'human_5.jpg', shortDescription: 'Повседневная классика.', category: 'Human'},
    {id: uuidv4(), price: 450000, title: 'Городской квартал', description: 'Здание городского квартала.', image: 'house_6.jpg', shortDescription: 'Новостройка.', category: 'House'},
    {id: uuidv4(), price: 700000, title: 'Купе', description: 'Эффектное купе.', image: 'car_6.jpg', shortDescription: 'Выразительная форма.', category: 'Car'},
    {id: uuidv4(), price: 18000, title: 'Куртка осенняя', description: 'Теплая куртка на осень.', image: 'human_6.jpg', shortDescription: 'Уютная защита.', category: 'Human'},
    {id: uuidv4(), price: 600000, title: 'Загородный особняк', description: 'Просторная загородная резиденция.', image: 'house_7.jpg', shortDescription: 'Свежесть природы.', category: 'House'},
    {id: uuidv4(), price: 1100000, title: 'Кабриолет', description: 'Открытый спортивный автомобиль.', image: 'car_7.jpg', shortDescription: 'Свободный ветер.', category: 'Car'},
    {id: uuidv4(), price: 25000, title: 'Коллекция нижнего белья', description: 'Нежное нижнее белье.', image: 'human_7.jpg', shortDescription: 'Интимный шик.', category: 'Human'},
    {id: uuidv4(), price: 550000, title: 'Экономичное жильё', description: 'Доступное экономическое жилье.', image: 'house_8.jpg', shortDescription: 'Просто и удобно.', category: 'House'},
    {id: uuidv4(), price: 850000, title: 'Среднего класса авто', description: 'Авто среднего ценового сегмента.', image: 'car_8.jpg', shortDescription: 'Оптимальный выбор.', category: 'Car'},
    {id: uuidv4(), price: 15000, title: 'Сумочка женский аксессуар', description: 'Женская сумочка элегантного дизайна.', image: 'human_8.jpg', shortDescription: 'Идеально дополняет образ.', category: 'Human'},
    {id: uuidv4(), price: 750000, title: 'Квартира-студия', description: 'Светлая квартира-студия.', image: 'house_9.jpg', shortDescription: 'Минимализм и простор.', category: 'House'},
    {id: uuidv4(), price: 950000, title: 'Электромобиль', description: 'Энергосберегающий электромобиль.', image: 'car_9.jpg', shortDescription: 'Экологически чистый транспорт.', category: 'Car'},
    {id: uuidv4(), price: 22000, title: 'Косметика декоративная', description: 'Профессиональная косметика.', image: 'human_9.jpg', shortDescription: 'Подчеркнет красоту.', category: 'Human'},
    {id: uuidv4(), price: 900000, title: 'Коттедж с садом', description: 'Коттедж с собственным садовым участком.', image: 'house_10.jpg', shortDescription: 'Иметь собственный уголок.', category: 'House'},
    {id: uuidv4(), price: 1300000, title: 'Премиум-внедорожник', description: 'Автоматизированный премиальный внедорожник.', image: 'car_10.jpg', shortDescription: 'Для настоящих приключений.', category: 'Car'},
    {id: uuidv4(), price: 30000, title: 'Парфюм мужские ароматы', description: 'Строгие и изысканные ароматы.', image: 'human_10.jpg', shortDescription: 'Создают атмосферу мужественности.', category: 'Human'},
    {id: uuidv4(), price: 1100000, title: 'Панельный жилой комплекс', description: 'Большой панельный жилой комплекс.', image: 'house_11.jpg', shortDescription: 'Масштабная застройка.', category: 'House'},
    {id: uuidv4(), price: 1400000, title: 'Хэтчбек', description: 'Маневренный хэтчбек.', image: 'car_11.jpg', shortDescription: 'Эффективность и компактность.', category: 'Car'},
    {id: uuidv4(), price: 35000, title: 'Кухонные принадлежности', description: 'Комплект кухонных принадлежностей.', image: 'human_11.jpg', shortDescription: 'Делают кухню функциональной.', category: 'Human'},
    {id: uuidv4(), price: 1300000, title: 'Замок-дворец', description: 'Старинный замок-дворец.', image: 'house_12.jpg', shortDescription: 'Историческое наследие.', category: 'House'},
    {id: uuidv4(), price: 1600000, title: 'Седан бизнес-класса', description: 'Автомобиль представительского класса.', image: 'car_12.jpg', shortDescription: 'Королевская роскошь.', category: 'Car'},
    {id: uuidv4(), price: 40000, title: 'Мужская обувь', description: 'Высококачественная мужская обувь.', image: 'human_12.jpg', shortDescription: 'Стильно и качественно.', category: 'Human'},
    {id: uuidv4(), price: 1500000, title: 'Пригородный посёлок', description: 'Квартиры пригородного посёлка.', image: 'house_13.jpg', shortDescription: 'Тишина вдали от суеты.', category: 'House'},
    {id: uuidv4(), price: 1800000, title: 'Универсал', description: 'Универсальная вместительная машина.', image: 'car_13.jpg', shortDescription: 'Пространство и возможности.', category: 'Car'},
    {id: uuidv4(), price: 45000, title: 'Акварельные краски', description: 'Художественные акварели.', image: 'human_13.jpg', shortDescription: 'Творческий потенциал.', category: 'Human'},
    {id: uuidv4(), price: 1700000, title: 'Элитная недвижимость', description: 'Элитная жилая площадь.', image: 'house_14.jpg', shortDescription: 'Особое пространство.', category: 'House'},
    {id: uuidv4(), price: 2000000, title: 'Гиперкар', description: 'Автолюбительская мечта.', image: 'car_14.jpg', shortDescription: 'Максимальные скорости.', category: 'Car'},
    {id: uuidv4(), price: 50000, title: 'Спальный комплект', description: 'Натуральный спальный комплект.', image: 'human_14.jpg', shortDescription: 'Забота о вашем сне.', category: 'Human'},
    {id: uuidv4(), price: 1900000, title: 'Частный бунгало', description: 'Собственный островной отдых.', image: 'house_15.jpg', shortDescription: 'Уединенность и красота.', category: 'House'},
    {id: uuidv4(), price: 2200000, title: 'Гидроцикл', description: 'Водный спорт и развлечения.', image: 'car_15.jpg', shortDescription: 'Активный отдых.', category: 'Car'},
    {id: uuidv4(), price: 55000, title: 'Постельное бельё', description: 'Настроит на хороший сон.', image: 'human_15.jpg', shortDescription: 'Ваш комфорт.', category: 'Human'},
    {id: uuidv4(), price: 2100000, title: 'Небольшой гостиничный номер', description: 'Номер отеля в городе.', image: 'house_16.jpg', shortDescription: 'Уютное размещение.', category: 'House'},
    {id: uuidv4(), price: 2400000, title: 'Трактора сельскохозяйственного назначения', description: 'Крупногабаритный трактор.', image: 'car_16.jpg', shortDescription: 'Производительность и мощность.', category: 'Car'},
    {id: uuidv4(), price: 60000, title: 'Электрочайники', description: 'Электрические чайники разного дизайна.', image: 'human_16.jpg', shortDescription: 'Сделайте утро ярче.', category: 'Human'},
    {id: uuidv4(), price: 2300000, title: 'Роскошная дача', description: 'Шикарный дачный участок.', image: 'house_17.jpg', shortDescription: 'Летний отдых.', category: 'House'},
    {id: uuidv4(), price: 2600000, title: 'Грузовики специального назначения', description: 'Специализированные грузовики.', image: 'car_17.jpg', shortDescription: 'Транспортировка крупногабаритов.', category: 'Car'},
    {id: uuidv4(), price: 65000, title: 'Фотоаппарат зеркальный', description: 'Цифровой фотоаппарат высокого качества.', image: 'human_17.jpg', shortDescription: 'Фотографируйте профессионально.', category: 'Human'},
    {id: uuidv4(), price: 2500000, title: 'Экспериментальное жилище', description: 'Проект экспериментального жилья.', image: 'house_18.jpg', shortDescription: 'Будущее архитектуры.', category: 'House'},
    {id: uuidv4(), price: 2800000, title: 'Микроавтобусы туристического направления', description: 'Туристический микроавтобус.', image: 'car_18.jpg', shortDescription: 'Путешествия становятся доступнее.', category: 'Car'},
    {id: uuidv4(), price: 70000, title: 'Умные часы', description: 'Электронные умные часы.', image: 'human_18.jpg', shortDescription: 'Следите за здоровьем.', category: 'Human'},
    {id: uuidv4(), price: 2700000, title: 'Фешенебельная студия', description: 'Элитная фешенебельная студия.', image: 'house_19.jpg', shortDescription: 'Роскошь в интерьере.', category: 'House'},
    {id: uuidv4(), price: 3000000, title: 'Комфортабельный лимузин', description: 'Комфортабельный лимузин.', image: 'car_19.jpg', shortDescription: 'Покажите статус.', category: 'Car'},
    {id: uuidv4(), price: 75000, title: 'Кроссовки спортивные', description: 'Качественные кроссовки.', image: 'human_19.jpg', shortDescription: 'Тренировки станут приятнее.', category: 'Human'},
    {id: uuidv4(), price: 2900000, title: 'Эко-квартира', description: 'Энергоэффективная экоквартира.', image: 'house_20.jpg', shortDescription: 'Живите экологично.', category: 'House'},
    {id: uuidv4(), price: 3200000, title: 'Легковой автомобиль премиум-класса', description: 'Машина престижного уровня.', image: 'car_20.jpg', shortDescription: 'Исключительное качество.', category: 'Car'},
    {id: uuidv4(), price: 80000, title: 'Набор посуды', description: 'Набор столовой посуды.', image: 'human_20.jpg', shortDescription: 'Ваша кухня станет красивой.', category: 'Human'}
];